Adding debugging step

diff --git a/.github/workflows/gpu-container-AutoDeployTrigger-9a2410cd-d700-45b1-af2d-6a7efeca30f1.yml b/.github/workflows/gpu-container-AutoDeployTrigger-9a2410cd-d700-45b1-af2d-6a7efeca30f1.yml
--- a/.github/workflows/gpu-container-AutoDeployTrigger-9a2410cd-d700-45b1-af2d-6a7efeca30f1.yml
+++ b/.github/workflows/gpu-container-AutoDeployTrigger-9a2410cd-d700-45b1-af2d-6a7efeca30f1.yml
@@ -92,7 +92,15 @@ jobs:
               ] |
               .containerDefinitions[0].logConfiguration.options."awslogs-region" = $aws_region' \
               task-definition-base.json > task-definition-modified.json
-
+      
+      - name: Debug task definition
+        run: |
+          echo "Checking JSON validity..."
+          echo "----- BEGIN JSON FILE -----"
+          cat task-definition-modified.json
+          echo "----- END JSON FILE -----"
+          echo "Validating with jq..."
+          jq . task-definition-modified.json || echo "JSON validation failed"
         
       - name: Fill in the new image ID in the Amazon ECS task definition
         id: task-def
